global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:8000
        labels:
          service: backend
  - job_name: downloader
    metrics_path: /metrics
    static_configs:
      - targets:
          - downloader:8082
        labels:
          service: downloader
  - job_name: telethon_worker
    metrics_path: /metrics
    static_configs:
      - targets:
          - telethon_worker:8090
        labels:
          service: telethon_worker
  - job_name: bot
    metrics_path: /metrics
    static_configs:
      - targets:
          - bot:8443
        labels:
          service: bot
  - job_name: node_exporter
    static_configs:
      - targets:
          - node_exporter:9100

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
